pipeline {
    environment {
        registry = "rajourad/mynginx"
        registryCredential = 'dockerhub_credential'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Cloning from GIT') {
            steps { 
                git branch: 'main', url: 'https://github.com/dkrajoura/KubernetesDemo.git' 
            }
        }
        stage('Building Image') { 
            steps {
                script { 
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
            }
        }
        stage('Deploy Image') {
            steps {
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    } 
                }
            }
        }
        stage('Cleaning up') {
            steps {
                sh "docker rmi $registry:$BUILD_NUMBER"
            }
        }
    }
}
