apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: my-helm-demo
spec: 
  replicas: 2
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavilable: 1
      maxSurge: 1
  selector: 
    matchLabels:
      app: {{ .Values.app.anme }}
  template:
    metadata: 
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image.repository }}/{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: config-{{ .Values.app.name }}
        ports:
        - name: http-{{ .Values.app.name }}
          protocol: TCP
